-- Create a temporary table for the lenses data
CREATE TEMP TABLE lens_data (
    cat text,
    subcat text,
    prod_name text
);

-- Insert the provided data
INSERT INTO lens_data (cat, subcat, prod_name) VALUES
-- ZSeries
('Lentes', 'ZSeries', 'Z Teleconventer TC-2.0x'),
('Lentes', 'ZSeries', 'Nikkor Z 100-400mm f/4.5-5.6 VR S'),
('Lentes', 'ZSeries', 'Nikkor Z 135mm F 1.8 S Plena'),
('Lentes', 'ZSeries', 'Nikkor Z 14-24mm F 2.8 S'),
('Lentes', 'ZSeries', 'Nikkor Z 14-30mm F 4.0 S'),
('Lentes', 'ZSeries', 'Nikkor Z 17-28mm F 2.8'),
('Lentes', 'ZSeries', 'Nikkor Z 180-600mm F 5.6-6.3 VR'),
('Lentes', 'ZSeries', 'Nikkor Z 20mm F 1.8 S'),
('Lentes', 'ZSeries', 'Nikkor Z 24-105mm f/4-7.1'),
('Lentes', 'ZSeries', 'Nikkor Z 24-120mm F 4.0 S'),
('Lentes', 'ZSeries', 'Nikkor Z 24-200mm F 4-6.3 VR'),
('Lentes', 'ZSeries', 'Nikkor Z 24-50mm F 4-6.3'),
('Lentes', 'ZSeries', 'Nikkor Z 24-70mm F 2.8 S'),
('Lentes', 'ZSeries', 'Nikkor Z 24-70mm F 4.0 S'),
('Lentes', 'ZSeries', 'Nikkor Z 24-70mm f/2.8 S II'),
('Lentes', 'ZSeries', 'Nikkor Z 24mm F 1.8 S'),
('Lentes', 'ZSeries', 'Nikkor Z 26mm F 2.8'),
('Lentes', 'ZSeries', 'Nikkor Z 28-135mm f/4 PZ'),
('Lentes', 'ZSeries', 'Nikkor Z 28-400mm F 4-8 VR'),
('Lentes', 'ZSeries', 'Nikkor Z 28-75mm F 2.8'),
('Lentes', 'ZSeries', 'Nikkor Z 28mm F 2.8'),
('Lentes', 'ZSeries', 'Nikkor Z 28mm F 2.8 (SE)'),
('Lentes', 'ZSeries', 'Nikkor Z 35mm F 1.4'),
('Lentes', 'ZSeries', 'Nikkor Z 35mm F 1.8 S'),
('Lentes', 'ZSeries', 'Nikkor Z 35mm f/1.2 S'),
('Lentes', 'ZSeries', 'Nikkor Z 400mm F 2.8 TC VR S'),
('Lentes', 'ZSeries', 'Nikkor Z 400mm F 4.5 VR S'),
('Lentes', 'ZSeries', 'Nikkor Z 40mm F 2.0'),
('Lentes', 'ZSeries', 'Nikkor Z 40mm F 2.0 (SE)'),
('Lentes', 'ZSeries', 'Nikkor Z 50mm F 1.2 S'),
('Lentes', 'ZSeries', 'Nikkor Z 50mm F 1.4'),
('Lentes', 'ZSeries', 'Nikkor Z 50mm F 1.8 S'),
('Lentes', 'ZSeries', 'Nikkor Z 58mm F 0.95 S Noct.'),
('Lentes', 'ZSeries', 'Nikkor Z 600mm F 4.0 TC VR S'),
('Lentes', 'ZSeries', 'Nikkor Z 600mm F 6.3 VR S'),
('Lentes', 'ZSeries', 'Nikkor Z 70-180mm F 2.8'),
('Lentes', 'ZSeries', 'Nikkor Z 70-200mm F 2.8 S VR'),
('Lentes', 'ZSeries', 'Nikkor Z 70-200mm f/2.8 VR S II'),
('Lentes', 'ZSeries', 'Nikkor Z 800mm F 6.3 VR S'),
('Lentes', 'ZSeries', 'Nikkor Z 85mm F 1.2 S'),
('Lentes', 'ZSeries', 'Nikkor Z 85mm F 1.8 S'),
('Lentes', 'ZSeries', 'Nikkor Z DX 12-28mm F 3.5-5.6 PZ VR'),
('Lentes', 'ZSeries', 'Nikkor Z DX 16-50mm F 3.5-6.3 VR'),
('Lentes', 'ZSeries', 'Nikkor Z DX 16-50mm F 3.5-6.3 VR - Silver'),
('Lentes', 'ZSeries', 'Nikkor Z DX 16-50mm f/2.8 VR'),
('Lentes', 'ZSeries', 'Nikkor Z DX 18-140mm F 3.5-6.3 VR DX'),
('Lentes', 'ZSeries', 'Nikkor Z DX 24mm F 1.7'),
('Lentes', 'ZSeries', 'Nikkor Z DX 50-250mm F 4.5-6.3 VR'),
('Lentes', 'ZSeries', 'Nikkor Z DX MC 35mm F 1.7'),
('Lentes', 'ZSeries', 'Nikkor Z MC 105mm F 2.8 VR S MACRO'),
('Lentes', 'ZSeries', 'Nikkor Z MC 50mm F 2.8 MACRO'),
('Lentes', 'ZSeries', 'Z Teleconventer TC-1.4x'),

-- Réflex
('Lentes', 'Réflex', 'AF VR Zoom-Nikkor 80-400mm f/4.5-5.6D ED'),
('Lentes', 'Réflex', 'AF-S DX Zoom-Nikkor 17-55mm f/2.8 G IF-ED'),
('Lentes', 'Réflex', 'AF-S II Teleconvertidor TC-14E'),
('Lentes', 'Réflex', 'AF-S Nikkor 120-300mm f/2.8E FL ED SR VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 200-400mm f/4G ED VR II'),
('Lentes', 'Réflex', 'AF-S Nikkor 200-500mm f/5.6E ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 24-70mm f/2.8G ED'),
('Lentes', 'Réflex', 'AF-S Nikkor 300 mm f/2.8 G ED VR II'),
('Lentes', 'Réflex', 'AF-S Nikkor 400mm f/2.8G ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 500mm f/4E FL ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 500mm f/4G ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 800mm f/5.6E FL ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor F/2G 200mm ED VR II'),
('Lentes', 'Réflex', 'AF-S Teleconventer TC-17E II'),
('Lentes', 'Réflex', 'AF-S Teleconventer TC-20E III'),
('Lentes', 'Réflex', 'Nikkor 600mm F 4.0 AF-S G ED VR'),
('Lentes', 'Réflex', 'AF DC-Nikkor 105mm f/2D'),
('Lentes', 'Réflex', 'AF DC-Nikkor 135mm f/2D'),
('Lentes', 'Réflex', 'AF Nikkor 50mm f/1.8D'),
('Lentes', 'Réflex', 'AF Nikkor 85mm f/1.4D IF'),
('Lentes', 'Réflex', 'AF-S 50mm f/1.8G'),
('Lentes', 'Réflex', 'AF-S DX Nikkor 18-55mm f/3.5-5.6 G VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 105mm f/1.4E ED'),
('Lentes', 'Réflex', 'AF-S Nikkor 300mm f/4D IF-ED'),
('Lentes', 'Réflex', 'Nikkor AF-S 50mm F 1.8G'),
('Lentes', 'Réflex', 'AF DX Ojo de Pez-Nikkor 10.5D mm f/2.8 G ED'),
('Lentes', 'Réflex', 'AF DX Ojo de Pez-Nikkor 10.5D mm f/2.8 G ED'),
('Lentes', 'Réflex', 'AF Nikkor 14mm f/2.8D ED'),
('Lentes', 'Réflex', 'AF Nikkor 180mm f/2.8D IF-ED'),
('Lentes', 'Réflex', 'AF Nikkor 20mm f/2.8D'),
('Lentes', 'Réflex', 'AF Nikkor 24mm f/2.8D'),
('Lentes', 'Réflex', 'AF Nikkor 28mm f/2.8D'),
('Lentes', 'Réflex', 'AF Nikkor 35mm f/2D'),
('Lentes', 'Réflex', 'AF Nikkor 50mm f/1.4D'),
('Lentes', 'Réflex', 'AF Zoom Nikkor 70-300mm f/4-5.6G'),
('Lentes', 'Réflex', 'AF Zoom-Nikkor 24-85mm f/2.8-4D'),
('Lentes', 'Réflex', 'AF-P DX Nikkor 10-20mm F 4.5-5.6G VR'),
('Lentes', 'Réflex', 'AF-P DX Nikkor 18-55mm f/3.5-5.6G VR'),
('Lentes', 'Réflex', 'AF-P DX Nikkor 70-300mm f/4.5-6.3G ED'),
('Lentes', 'Réflex', 'AF-P DX Nikkor 70-300mm f/4.5-6.3G ED VR'),
('Lentes', 'Réflex', 'AF-P Nikkor 70-300mm f/4.5-5.6E ED VR'),
('Lentes', 'Réflex', 'AF-S 14-24mm f/2.8 G ED Nikkor'),
('Lentes', 'Réflex', 'AF-S DX Micro-Nikkor 85mm F 3.5G ED VR'),
('Lentes', 'Réflex', 'AF-S DX Nikkor 16-80mm f/2.8-4E ED VR'),
('Lentes', 'Réflex', 'AF-S DX Nikkor 16-85mm f/3.5-5.6 G ED VR'),
('Lentes', 'Réflex', 'AF-S DX Nikkor 18-105mm f/3.5-5.6G ED VR'),
('Lentes', 'Réflex', 'AF-S DX Nikkor 18-140mm F 3.5-5.6G ED VR'),
('Lentes', 'Réflex', 'AF-S DX Nikkor 18-200mm f/3.5-5.6G ED VR II'),
('Lentes', 'Réflex', 'AF-S DX Nikkor 18-300mm F 3.5-6.3G ED VR'),
('Lentes', 'Réflex', 'AF-S DX Nikkor 18-300mm f/3.5-5.6G ED VR'),
('Lentes', 'Réflex', 'AF-S DX Nikkor 18-55mm f/3.5-5.6G VR II'),
('Lentes', 'Réflex', 'AF-S DX Nikkor 55-200mm f/4-5.6G ED VR II'),
('Lentes', 'Réflex', 'AF-S DX Nikkor 55-300mm f/4.5-5.6G ED VR'),
('Lentes', 'Réflex', 'AF-S DX VR Zoom- Nikkor 55-200mm f/4-5.6G IF-ED'),
('Lentes', 'Réflex', 'AF-S DX Zoom-Nikkor 10-24mm f/3.5-4.5G ED'),
('Lentes', 'Réflex', 'AF-S DX Zoom-Nikkor 12-24mm f/4G IF-ED'),
('Lentes', 'Réflex', 'AF-S DX Zoom-Nikkor 18-55mm f/3.5-5.6G ED II'),
('Lentes', 'Réflex', 'AF-S DX Zoom-Nikkor 55-200mm f/4-5.6G ED'),
('Lentes', 'Réflex', 'AF-S Nikkor 16-35mm f/4G ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 18-35mm f/3.5-4.5G ED'),
('Lentes', 'Réflex', 'AF-S Nikkor 20mm f/1.8G ED'),
('Lentes', 'Réflex', 'AF-S Nikkor 24-120mm f/4G ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 24-85 mm f/3.5-4.5G ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 24mm f/1.4G ED'),
('Lentes', 'Réflex', 'AF-S Nikkor 28-300mm f/3.5-5.6G ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 28mm f/1.8G'),
('Lentes', 'Réflex', 'AF-S Nikkor 300mm f/4E PF ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 35mm f/1.8G ED'),
('Lentes', 'Réflex', 'AF-S Nikkor 500mm f/5.6E PF ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 50mm F 1.4G'),
('Lentes', 'Réflex', 'AF-S Nikkor 50mm f/1.8G Edición Especial'),
('Lentes', 'Réflex', 'AF-S Nikkor 58mm f/1.4G'),
('Lentes', 'Réflex', 'AF-S Nikkor 600mm f/4E FL ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 70-200mm F 2.8 E FL ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 70-200mm f/2.8G ED VR II'),
('Lentes', 'Réflex', 'AF-S Nikkor 70-200mm f/4G ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 80-400mm f/4.5-5.6G ED VR'),
('Lentes', 'Réflex', 'AF-S Nikkor 85mm f/1.4G'),
('Lentes', 'Réflex', 'AF-S VR Zoom-Nikkor 70-300mm f/4.5-5.6G IF-ED'),
('Lentes', 'Réflex', 'AF-S Zoom-Nikkor 17-35mm f/2.8 D IF-ED'),
('Lentes', 'Réflex', 'Lente 35mm f1.8 AF-S con Filtro Nikon 52mm NC'),
('Lentes', 'Réflex', 'Micro-Nikkor AF-S 40mm 2.8 G DX'),
('Lentes', 'Réflex', 'Nikkor AF-S 24-70mm F 2.8 E ED VR'),
('Lentes', 'Réflex', 'Nikkor AF-S 35mm F 1.8G DX'),
('Lentes', 'Réflex', 'Nikkor AF-S 85mm f/1.8G'),
('Lentes', 'Réflex', 'AF-S Nikkor 35mm f/1.4G'),
('Lentes', 'Réflex', 'Nikkor 35mm f/1.4'),
('Lentes', 'Réflex', 'Nikkor 50mm f/1.2'),
('Lentes', 'Réflex', 'AF Ojo de Pez Nikkor 16mm f/2.8D'),
('Lentes', 'Réflex', 'AF-S FISHEYE Nikkor 8-15mm f/3.5-4.5E ED'),
('Lentes', 'Réflex', 'PC-E Micro Nikkor 45mm f/2.8D ED'),
('Lentes', 'Réflex', 'PC-E Micro-Nikkor 85mm f/2.8D II'),
('Lentes', 'Réflex', 'PC-E Nikkor 24mm f/3.5D ED'),
('Lentes', 'Réflex', 'AF Micro-Nikkor 200mm f/4D IF-ED'),
('Lentes', 'Réflex', 'AF Micro-Nikkor 60 mm f/2.8 D'),
('Lentes', 'Réflex', 'Micro-Nikkor AF-S 105mm F 2.8G IF-ED VR'),
('Lentes', 'Réflex', 'Micro-Nikkor AF-S 60mm f/2.8G ED'),
('Lentes', 'Réflex', 'AF-S Teleconventer TC-20E II');

-- Update existing products that match names to ensure correct categorization and state
UPDATE public.products p
SET 
  category = ld.cat,
  subcategory = ld.subcat,
  publish = 1,
  status = 'En Venta'
FROM lens_data ld
WHERE p.name = ld.prod_name;

-- Insert new products that don't satisfy the condition
INSERT INTO public.products (id, name, category, subcategory, status, publish, price, description)
SELECT DISTINCT
  'LENS_' || md5(ld.prod_name), -- Generate unique ID
  ld.prod_name, 
  ld.cat, 
  ld.subcat, 
  'En Venta', 
  1, 
  0, 
  'Lente Nikon'
FROM lens_data ld
WHERE NOT EXISTS (SELECT 1 FROM public.products p WHERE p.name = ld.prod_name)
ON CONFLICT (id) DO NOTHING;

-- Clean up
DROP TABLE lens_data;
